---
title: "fish_nutrition"
author: "Noam Altman-Kurosaki"
date: "2024-10-15"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
# install.packages("librarian") # for using the shelf function

# install/load remaining packages
librarian::shelf(here, tidyverse, ggplot2, ggrepel, ggpubr, vegan, glmmTMB, car, effects, DHARMa, stringr, MuMIn, nlme, lme4, mgcv, emmeans, dplyr, knitr, rfishbase, segmented)

# functions

## Standard error
se <- function(x){
  sd(x)/sqrt(n())
}
```

# Read data

```{r read import data}
# url for the download of MCR fish time series on EDI
fish_url <- "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-mcr.6.63&entityid=ac2c7a859ce8595ec1339e8530b9ba50"

# read in via read.csv - should be 105452 observations of 26 variables
fish_df <- read.csv(file = fish_url, stringsAsFactors = T)
fish_df$Site <- as.factor(paste0("lter_", fish_df$Site))
fish_df <- fish_df %>%
  mutate(Coast = case_when(Site == "lter_1" ~ "North",
                                 Site == "lter_2" ~ "North",
                                 Site == "lter_3" ~ "East",
                                 Site == "lter_4" ~ "East",
                                 Site == "lter_5" ~ "West",
                                 Site == "lter_6" ~ "West"))
fish_df$Coast <- as.factor(fish_df$Coast)

# some weird -1 values for biomass - these are negligible but affect anlyses later on. Absolute value to deal with them
fish_df$Biomass <- abs(fish_df$Biomass)

# drop forereef - most fishing occurs in lagoon
fish_df <- droplevels(subset(fish_df, Habitat != "Forereef"))

# current transect column is numeric - not specific enough for modeling
fish_df$Transect_ID <- as.factor(paste0(fish_df$Site, "-", fish_df$Habitat, "-", fish_df$Transect))

# create column for each transect's unique ID
fish_df$Unique_ID <- as.factor(paste0(fish_df$Year, "-", fish_df$Transect_ID))

# read in fisheries data from organized cnh data
cnh <- read.csv(here::here("data", "annotated_roadside_fish_cnh.csv"), na.strings=c("","NA"))

# extract species that were IDed to lowest taxonomic resolution
target_species <- unique(na.omit(cnh$species))

# extract nutrient data for those fish
nutrients <- rfishbase::estimate(target_species) %>% dplyr::select(Species, Calcium:Zinc_u95)



```


```{r plot total biomass}
# condense fish_df to total biomass at transect level
total_biomass_df <- fish_df %>%
  dplyr::group_by(Year, Site, Habitat, Coast, Transect_ID) %>%
  summarise(Biomass_total  = sum(Biomass))

# take the means and standard errors of the biomass per year/site/habitat
mean_biomass_df <- total_biomass_df %>%
  dplyr::group_by(Year, Coast) %>%
  summarise(Biomass_mean  = mean(Biomass_total),
            Biomass_se  = se(Biomass_total))

(total_biomass_plot <-
  ggplot() +
  geom_point(data = mean_biomass_df, aes(x = Year, y = Biomass_mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = mean_biomass_df, aes(x = Year, ymin = Biomass_mean - Biomass_se,
                                            ymax = Biomass_mean + Biomass_se, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = mean_biomass_df, aes(x = Year, y = Biomass_mean, colour = Coast), linewidth = 1) +
  annotate("segment", x = 2006, xend = 2009, y = 40000, yend = 40000, linewidth = 2, colour = "grey") +

  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +

   labs(y = "Biomass (g) \n",
        x = "Year", title = "a. All fish biomass") +
  theme_classic())
```

```{r plot fished biomass}
# subset fish_df based on the target fish list
target_fisheries_df <- fish_df[fish_df$Taxonomy %in% target_species, ]

# condense to total biomass at transect level
total_fisheries_biomass <- target_fisheries_df %>%
  dplyr::group_by(Year, Site, Habitat, Coast, Transect_ID) %>%
  summarise(Biomass_total  = sum(Biomass))

# take the means and standard errors of the biomass per year/site/habitat
mean_fisheries_biomass_df <- total_fisheries_biomass %>%
  dplyr::group_by(Year, Coast) %>%
  summarise(Biomass_mean  = mean(Biomass_total),
            Biomass_se  = se(Biomass_total))

(fisheries_biomass_plot <-
  ggplot() +
  geom_point(data = mean_fisheries_biomass_df, aes(x = Year, y = Biomass_mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = mean_fisheries_biomass_df, aes(x = Year, ymin = Biomass_mean - Biomass_se,
                                            ymax = Biomass_mean + Biomass_se, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = mean_fisheries_biomass_df, aes(x = Year, y = Biomass_mean, colour = Coast), position = position_dodge(0.3),
             linewidth = 1) +
  annotate("segment", x = 2006, xend = 2009, y = 15000, yend = 15000, linewidth = 2, colour = "grey") +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +

   labs(y = "Biomass (g) \n",
        x = "Year", title = "a. Target fish biomass") +
  theme_classic()+
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  )

```

```{r panel graph, fig.height = 5, fig.width = 10}
(biomass_panel <-
  ggpubr::ggarrange(total_biomass_plot, fisheries_biomass_plot, common.legend = T, legend = "bottom"))
# ggsave(filename = "output/biomass_panel_v1.png", biomass_panel, height = 5, width = 10)
```

```{r glmer biomass}
# check data
hist(total_fisheries_biomass$Biomass_total)

# check if log transform will normalize data
hist(log(total_fisheries_biomass$Biomass_total + 1)) # yes

# add columns for each disturbance
total_fisheries_biomass <- total_fisheries_biomass %>%
    mutate(Bleaching = case_when( 2016 <= Year & Year <= 2019 ~ "Pre-disturbance",
                                 Year > 2019 ~ "Post-disturbance"),
           Cyclone = case_when(Year <= 2010 ~ "Pre-disturbance",
                                 2015 >= Year & Year > 2010 ~ "Post-disturbance"))


# model with glmmTMB
fisheries_biomass_glmer <- glmmTMB(Biomass_total ~ Year*Coast + (1|Transect_ID) + ar1(as.factor(Year) + 0 | Transect_ID), family = Gamma("log"), data = total_fisheries_biomass)

summary(fisheries_biomass_glmer)
Anova(fisheries_biomass_glmer)

#             Chisq Df Pr(>Chisq)    
# Year       22.297  1  2.336e-06 ***
# Coast      15.520  2  0.0004265 ***
# Year:Coast 26.606  2  1.669e-06 ***

plot(allEffects(fisheries_biomass_glmer))

# model nonlinear effects with GAM
fisheries_gam <- gamm(Biomass_total ~ s(Year, by = Coast) + Coast , correlation = corAR1(form = ~ Year | Transect_ID), family = Gamma("log"), data = total_fisheries_biomass)
summary(fisheries_gam$lme)
plot(fisheries_gam$gam)

#### effects of disturbance ----



# subset
cc_fisheries_biomass <- subset(total_fisheries_biomass, is.na(total_fisheries_biomass$Bleaching))
bl_fisheries_biomass <- subset(total_fisheries_biomass, is.na(total_fisheries_biomass$Cyclone))

# create new variable to model slopes - year_centered, refers to year relative to disturbance
cc_fisheries_biomass <- cc_fisheries_biomass %>%
  mutate(Year_centered = ifelse(Cyclone == "Pre-disturbance", Year - 2005, Year - 2010))

bl_fisheries_biomass <- bl_fisheries_biomass %>%
  mutate(Year_centered = ifelse(Bleaching == "Pre-disturbance", Year - 2015, Year - 2019))


# model
cc_fisheries_mod <- glmmTMB(Biomass_total ~ Year_centered*Cyclone*Coast + (1|Transect_ID), family = Gamma("log"), data = cc_fisheries_biomass)
summary(cc_fisheries_mod)
Anova(cc_fisheries_mod)
#                               Chisq Df Pr(>Chisq)    
# Year_centered                0.3201  1  0.5715610    
# Cyclone                     18.4966  1  1.702e-05 ***
# Coast                       17.2299  2  0.0001814 ***
# Year_centered:Cyclone        2.6620  1  0.1027720    
# Year_centered:Coast          5.2956  2  0.0708074 .  
# Cyclone:Coast               10.9865  2  0.0041145 ** 
# Year_centered:Cyclone:Coast  1.9410  2  0.3788985   
performance::r2(cc_fisheries_mod) # R2m = 0.20, R2c = 0.55

### within factor pairwise comparisons
emtrends(cc_fisheries_mod, pairwise ~ Coast | Cyclone, var = "Year_centered")
# $contrasts
# Cyclone = Post-disturbance:
#  contrast     estimate     SE  df z.ratio p.value
#  East - North  0.07979 0.0966 Inf   0.826  0.6868
#  East - West  -0.00848 0.1023 Inf  -0.083  0.9962
#  North - West -0.08826 0.1002 Inf  -0.881  0.6521
# 
# Cyclone = Pre-disturbance:
#  contrast     estimate     SE  df z.ratio p.value
#  East - North  0.24084 0.1000 Inf   2.409  0.0423
#  East - West   0.16752 0.0981 Inf   1.707  0.2025
#  North - West -0.07332 0.1019 Inf  -0.719  0.7520

emtrends(cc_fisheries_mod, pairwise ~ Cyclone | Coast, var = "Year_centered")
# $contrasts
# Coast = East:
#  contrast                               estimate     SE  df z.ratio p.value
#  (Post-disturbance) - (Pre-disturbance)  -0.0151 0.0976 Inf  -0.155  0.8770
# 
# Coast = North:
#  contrast                               estimate     SE  df z.ratio p.value
#  (Post-disturbance) - (Pre-disturbance)   0.1459 0.0993 Inf   1.470  0.1417
# 
# Coast = West:
#  contrast                               estimate     SE  df z.ratio p.value
#  (Post-disturbance) - (Pre-disturbance)   0.1609 0.1035 Inf   1.554  0.1203

# extract info needed to plot slopes
cyclone_emm <- emmeans::emmip(cc_fisheries_mod,
                   Cyclone | Coast ~ Year_centered,
                   at = list(Year_centered = seq(1,5,0.1)), plotit = F, CIs = T)
# back-transform modeled response variable 
cyclone_emm$yvar_trans <- exp(cyclone_emm$yvar)

# backtransform year_centered to the actual year for plotting
cyclone_emm <- cyclone_emm %>%
  mutate(Year = ifelse(Cyclone == "Pre-disturbance", Year_centered + 2005, Year_centered + 2010))



bl_fisheries_mod <- glmmTMB(Biomass_total ~ Year_centered*Bleaching*Coast + (1|Transect_ID), family = Gamma("log"), data = bl_fisheries_biomass)
summary(bl_fisheries_mod)
Anova(bl_fisheries_mod)
#                                 Chisq Df Pr(>Chisq)   
# Year_centered                  0.3917  1   0.531410   
# Bleaching                      6.9745  1   0.008268 **
# Coast                         10.4443  2   0.005396 **
# Year_centered:Bleaching        0.4208  1   0.516558   
# Year_centered:Coast            0.3750  2   0.829023   
# Bleaching:Coast                9.1085  2   0.010522 * 
# Year_centered:Bleaching:Coast  0.7990  2   0.670659   
plot(allEffects(bl_fisheries_mod))
performance::r2(bl_fisheries_mod) # R2m = 0.14, R2c = 0.56
emtrends(bl_fisheries_mod, pairwise ~ Coast | Bleaching, var = "Year_centered")
# $contrasts
# Bleaching = Post-disturbance:
#  contrast     estimate    SE  df z.ratio p.value
#  East - North -0.09556 0.116 Inf  -0.821  0.6898
#  East - West  -0.10722 0.115 Inf  -0.934  0.6185
#  North - West -0.01166 0.117 Inf  -0.100  0.9945
# 
# Bleaching = Pre-disturbance:
#  contrast     estimate    SE  df z.ratio p.value
#  East - North  0.00176 0.116 Inf   0.015  0.9999
#  East - West   0.03881 0.123 Inf   0.317  0.9462
#  North - West  0.03706 0.122 Inf   0.304  0.9502

emtrends(bl_fisheries_mod, pairwise ~ Bleaching | Coast, var = "Year_centered")
# $contrasts
# Coast = East:
#  contrast                               estimate    SE  df z.ratio p.value
#  (Post-disturbance) - (Pre-disturbance)  -0.0344 0.115 Inf  -0.299  0.7651
# 
# Coast = North:
#  contrast                               estimate    SE  df z.ratio p.value
#  (Post-disturbance) - (Pre-disturbance)   0.0630 0.117 Inf   0.540  0.5893
# 
# Coast = West:
#  contrast                               estimate    SE  df z.ratio p.value
#  (Post-disturbance) - (Pre-disturbance)   0.1117 0.122 Inf   0.915  0.3601

# extract info needed to plot slopes
bleaching_emm <- emmeans::emmip(bl_fisheries_mod,
                   Bleaching | Coast ~ Year_centered,
                   at = list(Year_centered = seq(1,4,0.1)), plotit = F, CIs = T)
# back-transform modeled response variable 
bleaching_emm$yvar_trans <- exp(bleaching_emm$yvar)
# backtransform year_centered to the actual year for plotting
bleaching_emm <- bleaching_emm %>%
  mutate(Year = ifelse(Bleaching == "Pre-disturbance", Year_centered + 2015, Year_centered + 2019))

```

```{r plot models}
(cyclone_biomass <-
   ggplot(data = cyclone_emm) +
   geom_line(aes(x = Year, y = yvar_trans, colour = Coast)) +
   geom_ribbon(aes(x = Year, ymin = exp(LCL), ymax = exp(UCL), fill = Coast), alpha = 0.5) +
   geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
   labs(y = "Biomass (g) \n",
        x = "Year", title = "b. COTS and Cyclone") +
   scale_x_continuous(breaks = seq(2006, 2015, 3)) +
   theme_classic()  +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  
)

(bleaching_biomass <-
   ggplot(data = bleaching_emm) +
   geom_line(aes(x = Year, y = yvar_trans, colour = Coast)) +
   geom_ribbon(aes(x = Year, ymin = exp(LCL), ymax = exp(UCL), fill = Coast), alpha = 0.5) +
   geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Biomass (g) \n",
        x = "Year", title = "c. Bleaching") +
   scale_x_continuous(breaks = seq(2015, 2023, 3)) +
   theme_classic()  +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  
)

```
```{r biomass panel v2, fig.height = 10, fig.width=13}
(model_panel <-
  ggpubr::ggarrange(fisheries_biomass_plot, ggarrange(cyclone_biomass, bleaching_biomass, nrow = 1, ncol = 2, legend = "none"), ncol = 1, nrow = 2, common.legend = T, legend = "bottom", heights = c(0.45, 0.55)))
# ggsave(filename = "output/biomass_panel_v2.png", biomass_panel, height = 10, width = 13)
```


```{r segmented regression biomass, eval = FALSE}
### NOTE - HAVEN'T FIGURED THIS OUT YET!!! IGNORE FOR NOW!!!

# specify years for cutoffs in disturbance
disturbance <- c(2010, 2019) # note - can't use 2009 as a cutoff because it's too close to 2010 cyclone

# segmented trying first with standard glm
basemod <- glm(Biomass_total ~ Year + Coast, family = Gamma("log"), data = total_biomass_df)
# summary of coefficients with standard regression
summary(basemod) # biomass changes over time, but no real difference between coasts

seg_model <- segmented.glm(basemod, seg.Z = ~ Year, by = ~ Coast, psi = disturbance)

# summary of coefficients with segmented model
summary.segmented(seg_model) # no significant terms

x <- slope(seg_model, by = ~ Coast) # but we do see that slope flips direction in between the two major disturbances we could include

plot(seg_model)
# extract predicted and SE from model
fitted <- predict.segmented(seg_model, by = ~ Coast, interval = "confidence")

# add back-transformed predicted slopes to total_biomass_df
total_biomass_df$Predicted <- fitted[,1]

```

```{r multivariate fish community prep and permanova}
# create long-form time series of fish biomass per transect
target_fisheries_long <- target_fisheries_df %>%
  dplyr::group_by(Unique_ID, Year, Site, Habitat, Coast, Transect_ID, Taxonomy) %>%
  summarise(Biomass_total  = sum(Biomass))

# visualize how to transform data for ordination
hist(log(target_fisheries_long$Biomass_total+1)) # log transformation looks good!

# make wide df for ordination
target_fisheries_wide <- target_fisheries_long %>%
  pivot_wider(names_from = Taxonomy, values_from = Biomass_total, values_fill = list(Biomass_total = 0))

# add coast_year variable for calculating centroids
target_fisheries_wide$Coast_year <- paste0(target_fisheries_wide$Coast, "-", target_fisheries_wide$Year)
# vector for metadata columns to subset later
meta_cols <- c("Unique_ID", "Year", "Habitat", "Coast", "Coast_year", "Site", "Transect_ID")

# create meta_df for merge
meta_df <- target_fisheries_wide[,which(names(target_fisheries_wide) %in% meta_cols)]

# create matrix for ordination
fish_matrix <- as.matrix(target_fisheries_wide[,-which(names(target_fisheries_wide) %in% meta_cols)])
rownames(fish_matrix) <- target_fisheries_wide$Unique_ID # add rownames

# transform values
fish_matrix <- log(fish_matrix+1)

fish_rows_to_remove <- rowSums(fish_matrix) == 0 # check if there are any rows with no fish in matrix
# fish_matrix <- fish_matrix[!fish_rows_to_remove,] # all rows have values - don't need to remove anything

# conduct permanova
adonis2(fish_matrix ~ Year*Coast, data = target_fisheries_wide, method = "bray")

#             Df SumOfSqs      R2       F Pr(>F)    
# Year         1    4.423 0.02969 27.5679  0.001 ***
# Coast        2    5.788 0.03885 18.0381  0.001 ***
# Year:Coast   2    1.606 0.01078  5.0055  0.001 ***
# Residual   855  137.163 0.92069                   
# Total      860  148.979 1.00000             

#### compare effects of specific disturbances

## cots and cyclone - 2006 - 2010, after is 2011 - 2015
cc_pre <- droplevels(target_fisheries_wide[which(target_fisheries_wide$Year %in% c(2006:2010)),])
cc_pre$Pre.post <- rep("Pre", nrow(cc_pre))
cc_post <- droplevels(target_fisheries_wide[which(target_fisheries_wide$Year %in% c(2011:2015)),])
cc_post$Pre.post <- rep("Post", nrow(cc_post))

# combine pre and post disturbance
cc_comb <- rbind(cc_pre, cc_post)

# subset fish matrix for relevant years
cc_fish_matrix <- fish_matrix[which(rownames(fish_matrix) %in% cc_comb$Unique_ID),]


# test effects of cyclone
adonis2(cc_fish_matrix ~ Coast*Pre.post, data = cc_comb, method = "bray")
#                 Df SumOfSqs      R2       F Pr(>F)    
# Coast            2    4.891 0.05779 15.2506  0.001 ***
# Pre.post         1    3.382 0.03996 21.0895  0.001 ***
# Coast:Pre.post   2    0.828 0.00979  2.5825  0.004 ** 



## Bleaching in 2019 - 2016:2019 = pre, 2020-2023 = post
bl_pre <- droplevels(target_fisheries_wide[which(target_fisheries_wide$Year %in% c(2016:2019)),])
bl_pre$Pre.post <- rep("Pre", nrow(bl_pre))
bl_post <- droplevels(target_fisheries_wide[which(target_fisheries_wide$Year %in% c(2020:2023)),])
bl_post$Pre.post <- rep("Post", nrow(bl_post))

# combine pre and post disturbance
bl_comb <- rbind(bl_pre, bl_post)

# subset fish matrix for relevant years
bl_fish_matrix <- fish_matrix[which(rownames(fish_matrix) %in% bl_comb$Unique_ID),]


# test effects of bleaching
adonis2(bl_fish_matrix ~ Coast*Pre.post, data = bl_comb, method = "bray")
#                 Df SumOfSqs      R2       F Pr(>F)    
# Coast            2    2.240 0.03598 7.1950  0.001 ***
# Pre.post         1    0.789 0.01267 5.0661  0.001 ***
# Coast:Pre.post   2    0.391 0.00629 1.2572  0.252    



```


```{r nmds prep}
# conduct nmds - this takes a while
# set.seed(1032) 
# fish_ord <- metaMDS(fish_matrix, dist	= "bray", k = 2) 
# fish_ord # stress = 0.27 - pretty high

# set.seed(1032) 
# fish_ord_3 <- metaMDS(fish_matrix, dist	= "bray", k = 3) 
# fish_ord_3 # stress = 0.19 - still high

set.seed(1032) 
fish_ord_4 <- metaMDS(fish_matrix, dist	= "bray", k = 4) 
fish_ord_4 # stress = 0.145 - still high but much better - going 4D

# extract species scores
fish.species.scores <- as.data.frame(scores(fish_ord_4, "species")) 
fish.species.scores$Species <- rownames(fish.species.scores) 

# extract the site scores
fish.site.scores <- as.data.frame(scores(fish_ord_4, "sites"))  

# add back in metadata
fish.site.scores$Unique_ID <- rownames(fish.site.scores)
fish.site.scores <- merge(meta_df, fish.site.scores, by = "Unique_ID")

# calculate centroids
fish.cent <- aggregate(cbind(NMDS1, NMDS2) ~ Coast_year, data = fish.site.scores, FUN = mean) 
fish.cent <- merge(fish.cent, meta_df, by = "Coast_year")
```

```{r plot fish nmds, fig.height = 10, fig.width=10}
(fish_nmds <- 
  ggplot() +
  geom_point(fish.site.scores, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast), alpha = 0.4 )+
  geom_text_repel(fish.species.scores, mapping = aes(x = NMDS1, y = NMDS2, label = Species), max.overlaps = 14, alpha = 0.5) +
  geom_path(fish.cent, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast),
            arrow = arrow(length=unit(0.4,"cm"), ends="last", type = "closed"), size = 1) +
  geom_text(aes(x = 2.1, y = 1.2, label = "Stress = 0.14\nYear - P = 0.001\nCoast - P = 0.001\nYear X Coast - P = 0.001"),
            hjust = 1, size = 5) +
  labs(title = "a. Fish community") +
  theme_bw() + 
  theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) )

```

```{r disturbance ordination}

cc_fish_rows_to_remove <- rowSums(cc_fish_matrix) == 0 # check if there are any rows with no cc_fish in matrix
# cc_fish_matrix <- cc_fish_matrix[!cc_fish_rows_to_remove,] # all rows have values - don't need to remove anything
cc_fish_cols_to_remove <- colSums(cc_fish_matrix) == 0 # check if there are any species that are never present in matrix
cc_fish_matrix <- cc_fish_matrix[,!cc_fish_cols_to_remove] # remove those species (2 dropped)

# conduct nmds - this takes a while

# cc_fish_ord <- metaMDS(cc_fish_matrix, dist	= "bray", k = 2) 
# cc_fish_ord # stress = 0.27 - pretty high
# 
# cc_fish_ord_3 <- metaMDS(cc_fish_matrix, dist	= "bray", k = 3) 
# cc_fish_ord_3 # stress = 0.19 - still high 

set.seed(1032) 
cc_fish_ord_4 <- metaMDS(cc_fish_matrix, dist	= "bray", k = 4) 
cc_fish_ord_4 # stress = 0.14 - best

# extract species scores
cc_fish.species.scores <- as.data.frame(scores(cc_fish_ord_4, "species")) 
cc_fish.species.scores$Species <- rownames(cc_fish.species.scores) 

# extract the site scores
cc_fish.site.scores <- as.data.frame(scores(cc_fish_ord_4, "sites"))  

# add back in metadata
cc_fish.site.scores$Unique_ID <- rownames(cc_fish.site.scores)
cc_fish.site.scores <- merge(meta_df, cc_fish.site.scores, by = "Unique_ID")

# add pre-post variable
cc_fish.site.scores <- cc_fish.site.scores %>%
    mutate(Disturbance = case_when(Year <= 2010 ~ "Pre-disturbance",
                                 Year > 2010 ~ "Post-disturbance"))

# add pre.post_coast variable for calculating centroids/grouping
cc_fish.site.scores$Disturbance_coast <- paste0(cc_fish.site.scores$Coast, "_", cc_fish.site.scores$Disturbance)

# calculate centroids for path
cc_fish.cent <- aggregate(cbind(NMDS1, NMDS2) ~ Coast_year, data = cc_fish.site.scores, FUN = mean) 
cc_fish.cent <- merge(cc_fish.cent, meta_df, by = "Coast_year")


## BLEACHING


bl_fish_rows_to_remove <- rowSums(bl_fish_matrix) == 0 # check if there are any rows with no bl_fish in matrix
# bl_fish_matrix <- bl_fish_matrix[!bl_fish_rows_to_remove,] # all rows have values - don't need to remove anything
bl_fish_cols_to_remove <- colSums(bl_fish_matrix) == 0 # check if there are any species that are never present in matrix
bl_fish_matrix <- bl_fish_matrix[,!bl_fish_cols_to_remove] # remove those species (1 dropped)

# conduct nmds - this takes a while
# bl_fish_ord <- metaMDS(bl_fish_matrix, dist	= "bray", k = 2) 
# bl_fish_ord # stress = 0.25 - pretty high
# 
# bl_fish_ord_3 <- metaMDS(bl_fish_matrix, dist	= "bray", k = 3) 
# bl_fish_ord_3 # stress = 0.18 - still high 

set.seed(1032) 
bl_fish_ord_4 <- metaMDS(bl_fish_matrix, dist	= "bray", k = 4) 
bl_fish_ord_4 # stress = 0.13 - best

# extract species scores
bl_fish.species.scores <- as.data.frame(scores(bl_fish_ord_4, "species")) 
bl_fish.species.scores$Species <- rownames(bl_fish.species.scores) 

# extract the site scores
bl_fish.site.scores <- as.data.frame(scores(bl_fish_ord_4, "sites"))  

# add back in metadata
bl_fish.site.scores$Unique_ID <- rownames(bl_fish.site.scores)
bl_fish.site.scores <- merge(meta_df, bl_fish.site.scores, by = "Unique_ID")

# add pre-post variable
bl_fish.site.scores <- bl_fish.site.scores %>%
    mutate(Disturbance = case_when(Year <= 2019 ~ "Pre-disturbance",
                                 Year > 2019 ~ "Post-disturbance"))

# add pre.post_coast variable for calculating centroids/grouping
bl_fish.site.scores$Disturbance_coast <- paste0(bl_fish.site.scores$Coast, "_", bl_fish.site.scores$Disturbance)

bl_fish.cent <- aggregate(cbind(NMDS1, NMDS2) ~ Coast_year, data = bl_fish.site.scores, FUN = mean) 
bl_fish.cent <- merge(bl_fish.cent, meta_df, by = "Coast_year")
```

```{r disturbance nmds plot}

(cc_fish_nmds <-
  ggplot() +
  geom_point(data = cc_fish.site.scores, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast), alpha = 0.4 )+
  stat_ellipse(data = cc_fish.site.scores, 
                 mapping = aes(x = NMDS1, y = NMDS2, group = Disturbance_coast, linetype = Disturbance, color = Coast), type = "t") +
  geom_text_repel(fish.species.scores, mapping = aes(x = NMDS1, y = NMDS2, label = Species), max.overlaps = 15, alpha = 0.5) +
  geom_path(cc_fish.cent, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast),
            arrow = arrow(length=unit(0.4,"cm"), ends="last", type = "closed"), size = 1) +
  geom_text(aes(x = -1.4, y = -1.3, label = "Stress = 0.14\nDisturbance - P = 0.001\nCoast - P = 0.001\nDisturbance X Coast - P = 0.004"),
            hjust = 0, size = 4) +
  labs(title = "b. COTS and Cyclone") +
  scale_linetype_manual(values = c("Pre-disturbance" = "solid", "Post-disturbance" = "dashed")) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
#        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.6)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) 
    
)



# bleaching
(bl_fish_nmds <-
  ggplot() +
  geom_point(data = bl_fish.site.scores, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast), alpha = 0.4 )+
  stat_ellipse(data = bl_fish.site.scores, 
                 mapping = aes(x = NMDS1, y = NMDS2, group = Disturbance_coast, linetype = Disturbance, color = Coast), type = "t") +
  geom_text_repel(fish.species.scores, mapping = aes(x = NMDS1, y = NMDS2, label = Species), max.overlaps = 15, alpha = 0.5) +
  geom_path(bl_fish.cent, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast),
            arrow = arrow(length=unit(0.4,"cm"), ends="last", type = "closed"), size = 1) +
  geom_text(aes(x = 3.2, y = 1.05, label = "Stress = 0.13\nDisturbance - P = 0.001\nCoast - P = 0.002\nDisturbance X Coast - P = 0.27"),
            hjust = 1, size = 4) +
  scale_x_continuous(limits = c(-1.5, 3.2)) +
  labs(title = "c. Bleaching") +
  scale_linetype_manual(values = c("Pre-disturbance" = "solid", "Post-disturbance" = "dashed")) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) 
    
)
```

```{r fish nmds panel, fig.height=12, fig.width=11}
(biomass_ord_panel <- ggarrange(fish_nmds, ggarrange(cc_fish_nmds, bl_fish_nmds, ncol = 2, nrow = 1, legend = "none"), nrow = 2, heights = c(0.6, 0.4), common.legend = T, legend.grob = get_legend(cc_fish_nmds), legend = "bottom"))

# ggsave(filename = "output/biomass_ordination.png", biomass_ord_panel, height = 12, width = 11)
```

```{r calculate nutrients}
key_nutrients <- c("Calcium", "Iron", "Selenium", "VitaminA", "Zinc", "Protein", "Omega3")

# subset the modal estimates
nutrients_subset <- dplyr::select(nutrients, c("Species", key_nutrients))

# transform to nutrient densities per g of fish biomass
nutrients_subset[key_nutrients] <- nutrients_subset[key_nutrients]/100

# rename Species to Taxonomy for merge
colnames(nutrients_subset) <- c("Taxonomy", key_nutrients)

# merge with fisheries dataset
target_fisheries_df <- target_fisheries_df %>%
  left_join(nutrients_subset, by = "Taxonomy")

# calculate total nutrient content
target_fisheries_df <- target_fisheries_df %>%
  mutate(
    Calcium_amount = Calcium*Biomass,
    Iron_amount = Iron*Biomass,
    Selenium_amount = Selenium*Biomass,
    VitaminA_amount = VitaminA*Biomass,
    Zinc_amount = Zinc*Biomass,
    Protein_amount = Protein*Biomass,
    Omega3_amount = Omega3*Biomass
  )

# aggregate to get nutrient content per transect for ordination
nutrients_wide <- target_fisheries_df %>%
  group_by(Year, Habitat, Coast, Site, Transect_ID, Unique_ID) %>%
  summarise(Calcium_total = sum(Calcium_amount, na.rm = TRUE),
            Iron_total = sum(Iron_amount, na.rm = TRUE),
            Selenium_total = sum(Selenium_amount, na.rm = TRUE),
            VitaminA_total = sum(VitaminA_amount, na.rm = TRUE),
            Zinc_total = sum(Zinc_amount, na.rm = TRUE),
            Protein_total = sum(Protein_amount, na.rm = TRUE),
            Omega3_total = sum(Omega3_amount, na.rm = TRUE))


```

```{r univariate approach}
nutrients_long <- nutrients_wide %>%
  pivot_longer(cols = Calcium_total:Omega3_total, names_to = "Nutrient", values_to = "Amount")

# for subsetting 
macros <- c("Protein_total", "Omega3_total")

# create separate dataframes for macro and micronutrients
macros_long <- nutrients_long[nutrients_long$Nutrient %in% macros, ]
micros_long <- nutrients_long[!nutrients_long$Nutrient %in% macros, ]

macros_means <- macros_long %>%
  dplyr::group_by(Year, Coast, Nutrient) %>%
  summarise(Mean  = mean(Amount),
            SE  = se(Amount))
  

micros_means <- micros_long %>%
  dplyr::group_by(Year, Coast, Nutrient) %>%
  summarise(Mean  = mean(Amount),
            SE  = se(Amount))
```

```{r plot nutrient time series, fig.height = 8, fig.width=10}
(protein_plot <-
  ggplot() +
  geom_point(data = subset(macros_means, Nutrient == "Protein_total"), aes(x = Year, y = Mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = subset(macros_means, Nutrient == "Protein_total"), aes(x = Year, ymin = Mean - SE,
                                            ymax = Mean + SE, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = subset(macros_means, Nutrient == "Protein_total"), aes(x = Year, y = Mean, colour = Coast), linewidth = 1,
             position = position_dodge(0.3)) +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Nutrient availability (mg) \n",
        x = "Year", title = "a. Protein") +
  theme_classic())

(omega_plot <-
  ggplot() +
  geom_point(data = subset(macros_means, Nutrient == "Omega3_total"), aes(x = Year, y = Mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = subset(macros_means, Nutrient == "Omega3_total"), aes(x = Year, ymin = Mean - SE,
                                            ymax = Mean + SE, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = subset(macros_means, Nutrient == "Omega3_total"), aes(x = Year, y = Mean, colour = Coast), linewidth = 1,
             position = position_dodge(0.3)) +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Nutrient availability (mg) \n",
        x = "Year", title = "b. Omega 3") +
  theme_classic())


(calcium_plot <-
  ggplot() +
  geom_point(data = subset(micros_means, Nutrient == "Calcium_total"), aes(x = Year, y = Mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = subset(micros_means, Nutrient == "Calcium_total"), aes(x = Year, ymin = Mean - SE,
                                            ymax = Mean + SE, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = subset(micros_means, Nutrient == "Calcium_total"), aes(x = Year, y = Mean, colour = Coast), linewidth = 1,
             position = position_dodge(0.3)) +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Nutrient availability (mg) \n",
        x = "Year", title = "c. Calcium") +
  theme_classic())

(iron_plot <-
  ggplot() +
  geom_point(data = subset(micros_means, Nutrient == "Iron_total"), aes(x = Year, y = Mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = subset(micros_means, Nutrient == "Iron_total"), aes(x = Year, ymin = Mean - SE,
                                            ymax = Mean + SE, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = subset(micros_means, Nutrient == "Iron_total"), aes(x = Year, y = Mean, colour = Coast), linewidth = 1,
             position = position_dodge(0.3)) +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Nutrient availability (mg) \n",
        x = "Year", title = "d. Iron") +
  theme_classic())

(selenium_plot <-
  ggplot() +
  geom_point(data = subset(micros_means, Nutrient == "Selenium_total"), aes(x = Year, y = Mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = subset(micros_means, Nutrient == "Selenium_total"), aes(x = Year, ymin = Mean - SE,
                                            ymax = Mean + SE, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = subset(micros_means, Nutrient == "Selenium_total"), aes(x = Year, y = Mean, colour = Coast), linewidth = 1,
             position = position_dodge(0.3)) +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Nutrient availability (mg) \n",
        x = "Year", title = "e. Selenium") +
  theme_classic())

(vitaminA_plot <-
  ggplot() +
  geom_point(data = subset(micros_means, Nutrient == "VitaminA_total"), aes(x = Year, y = Mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = subset(micros_means, Nutrient == "VitaminA_total"), aes(x = Year, ymin = Mean - SE,
                                            ymax = Mean + SE, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = subset(micros_means, Nutrient == "VitaminA_total"), aes(x = Year, y = Mean, colour = Coast), linewidth = 1,
             position = position_dodge(0.3)) +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Nutrient availability (mg) \n",
        x = "Year", title = "f. Vitamin A") +
  theme_classic())

(zinc_plot <-
  ggplot() +
  geom_point(data = subset(micros_means, Nutrient == "Zinc_total"), aes(x = Year, y = Mean, colour = Coast), size = 3,
             position = position_dodge(0.3)) +
  geom_errorbar(data = subset(micros_means, Nutrient == "Zinc_total"), aes(x = Year, ymin = Mean - SE,
                                            ymax = Mean + SE, colour = Coast),
                width = 0, size = 0.5, position = position_dodge(0.3) )+
   geom_line(data = subset(micros_means, Nutrient == "Zinc_total"), aes(x = Year, y = Mean, colour = Coast), linewidth = 1,
             position = position_dodge(0.3)) +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 1) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 1) +
   labs(y = "Nutrient availability (mg) \n",
        x = "Year", title = "g. Zinc") +
  theme_classic())
```

```{r nutrients panel graph, fig.height = 10, fig.width=24}
ggarrange(protein_plot, omega_plot, calcium_plot, iron_plot, selenium_plot, vitaminA_plot, zinc_plot,
          nrow = 2, ncol = 4, common.legend = T)

```

```{r correlations between biomass and nutrients}
# create df with both nutrients and biomass
nutrients_and_biomass <- merge(nutrients_wide, total_fisheries_biomass, by = c("Year", "Site", "Habitat", "Coast", "Transect_ID"))

# create vector of nutrient column names from df
nutrient_cols <- c("Protein_total", "Omega3_total","Calcium_total", "Iron_total", "Selenium_total", "VitaminA_total", "Zinc_total")

# create vector for dataframe colnames
df_names <- c("Nutrient", "Kendall's Tau")

# create data frame for output - populated with NAs for now by creating matrix based on dimensions of the two vectors above
nutrient_correlations <- as.data.frame(matrix(nrow = length(nutrient_cols),
                                              ncol = length(df_names)))
# change colnames
colnames(nutrient_correlations) <- df_names

# test correlations of each nutrient with biomass
for(i in 1:length(nutrient_cols)){ # for each nutrient column
  # fill in the first row of the nutrient_correlations df with the nutrient we're looking at
  nutrient_correlations[i, 1] <-  sub("\\_.*", "", nutrient_cols[i] ) 
  
  # and its correlation with biomass
  nutrient_correlations[i,2] <- cor(x = nutrients_and_biomass$Biomass_total, y = nutrients_and_biomass[nutrient_cols[i]],
                                    method = "kendall") # using kendall over spearman due to skew in data
}

# View correlations
# View(nutrient_correlations) # generally strong correlations, but weaker for micronutrients

(protein_biomass <-
  ggplot() +
  geom_point(data = nutrients_and_biomass, aes(x = Biomass_total, y = Protein_total, colour = Coast), size = 3) +
    geom_text(aes(x = 115000, y = 1000, label = "tau == 0.99"), size = 8, parse = T, hjust = 1) +
   labs(y = "Protein (mg) \n",
        x = "Biomass", title = "a. Protein") +
   theme_classic() +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) )

(omega_biomass <-
  ggplot() +
  geom_point(data = nutrients_and_biomass, aes(x = Biomass_total, y = Omega3_total, colour = Coast), size = 3) +
    geom_text(aes(x = 115000, y = 8, label = "tau == 0.98"), size = 8, parse = T, hjust = 1) +
   labs(y = "Omega 3 (mg) \n",
        x = "Biomass", title = "b. Omega 3") +
  theme_classic()  +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")))

(calcium_biomass <-
  ggplot() +
  geom_point(data = nutrients_and_biomass, aes(x = Biomass_total, y = Calcium_total, colour = Coast), size = 3) +
    geom_text(aes(x = 115000, y = 3000, label = "tau == 0.92"), size = 8, parse = T, hjust = 1) +
   labs(y = "Calcium (mg) \n",
        x = "Biomass", title = "c. Calcium") +
  theme_classic() +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")))

(iron_biomass <-
  ggplot() +
  geom_point(data = nutrients_and_biomass, aes(x = Biomass_total, y = Iron_total, colour = Coast), size = 3) +
    geom_text(aes(x = 115000, y = 50, label = "tau == 0.83"), size = 8, parse = T, hjust = 1) +
   labs(y = "Iron (mg) \n",
        x = "Biomass", title = "d. Iron") +
  theme_classic() +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")))

(vitaminA_biomass <-
  ggplot() +
  geom_point(data = nutrients_and_biomass, aes(x = Biomass_total, y = VitaminA_total, colour = Coast), size = 3) +
    geom_text(aes(x = 115000, y = 1000, label = "tau == 0.81"), size = 8, parse = T, hjust = 1) +
   labs(y = "Vitamin A (mg) \n",
        x = "Biomass", title = "e. Vitamin A") +
  theme_classic() +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")))

(selenium_biomass <-
  ggplot() +
  geom_point(data = nutrients_and_biomass, aes(x = Biomass_total, y = Selenium_total, colour = Coast), size = 3) +
    geom_text(aes(x = 115000, y = 1000, label = "tau == 0.91"), size = 8, parse = T, hjust = 1) +
   labs(y = "Selenium (mg) \n",
        x = "Biomass", title = "f. Selenium") +
  theme_classic() +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")))

(zinc_biomass <-
  ggplot() +
  geom_point(data = nutrients_and_biomass, aes(x = Biomass_total, y = Zinc_total, colour = Coast), size = 3) +
  geom_text(aes(x = 115000, y = 100, label = "tau == 0.73"), size = 8, parse = T, hjust = 1) +
   labs(y = "Protein (mg) \n",
        x = "Biomass", title = "g. Zinc") +
  theme_classic() +
   theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 18),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")))
```

```{r nutrients panel graph, fig.height = 8, fig.width=20}
(nutrient_corr_panel <- ggarrange(protein_biomass, omega_biomass, calcium_biomass, iron_biomass, selenium_biomass, vitaminA_biomass, zinc_biomass, nrow = 2, ncol = 4, common.legend = T, legend = "bottom"))

# ggsave(filename = "output/biomass_nutrients_corr.png", nutrient_corr_panel, height = 8, width = 20)
```

```{r nutrients ordination setup and permanova}
# visualize possible transformations from nutrients long
hist(log(nutrients_long$Amount + 1)) # effectively bimodal - differences between macro and micronutrients?
hist(log(macros_long$Amount + 1)) # both dists are bimodal - might be okay?

# for merge later
nutrients_wide$Coast_year <- paste0(nutrients_wide$Coast, "-", nutrients_wide$Year)
# create matrix of nutrient data
nutrients_matrix <- as.matrix(nutrients_wide[,-which(names(nutrients_wide) %in% meta_cols)])
rownames(nutrients_matrix) <- nutrients_wide$Unique_ID


# transform values
nutrients_matrix <- log(nutrients_matrix+1)

# perform permanova
adonis2(nutrients_matrix ~ Coast*Year, data = nutrients_wide, method = "bray")
#             Df SumOfSqs      R2       F Pr(>F)    
# Coast        2   0.7651 0.05932 28.9246  0.001 ***
# Year         1   0.6602 0.05119 49.9187  0.001 ***
# Coast:Year   2   0.1646 0.01276  6.2211  0.001 ***


#### compare effects of specific disturbances

## cots and cyclone - 2006 - 2010, after is 2011 - 2015
cc_nutrients_pre <- droplevels(nutrients_wide[which(nutrients_wide$Year %in% c(2006:2010)),])
cc_nutrients_pre$Pre.post <- rep("Pre", nrow(cc_nutrients_pre))
cc_nutrients_post <- droplevels(nutrients_wide[which(nutrients_wide$Year %in% c(2011:2015)),])
cc_nutrients_post$Pre.post <- rep("Post", nrow(cc_nutrients_post))

# combine pre and post disturbance
cc_nutrients_comb <- rbind(cc_nutrients_pre, cc_nutrients_post)

# subset fish matrix for relevant years
cc_nutrients_matrix <- nutrients_matrix[which(rownames(nutrients_matrix) %in% cc_nutrients_comb$Unique_ID),]


# test effects of cyclone
adonis2(cc_nutrients_matrix ~ Coast*Pre.post, data = cc_nutrients_comb, method = "bray")
#                Df SumOfSqs      R2       F Pr(>F)    
#Coast            2   0.6131 0.07557 20.7152  0.001 ***
#Pre.post         1   0.4740 0.05843 32.0353  0.001 ***
#Coast:Pre.post   2   0.0559 0.00689  1.8877  0.126    
  



## Bleaching in 2019 - 2016:2019 = pre, 2020-2023 = post
bl_nutrients_pre <- droplevels(nutrients_wide[which(nutrients_wide$Year %in% c(2016:2019)),])
bl_nutrients_pre$Pre.post <- rep("Pre", nrow(bl_nutrients_pre))
bl_nutrients_post <- droplevels(nutrients_wide[which(nutrients_wide$Year %in% c(2020:2023)),])
bl_nutrients_post$Pre.post <- rep("Post", nrow(bl_nutrients_post))

# combine pre and post disturbance
bl_nutrients_comb <- rbind(bl_nutrients_pre, bl_nutrients_post)

# subset fish matrix for relevant years
bl_nutrients_matrix <- nutrients_matrix[which(rownames(nutrients_matrix) %in% bl_nutrients_comb$Unique_ID),]


# test effects of bleaching
adonis2(bl_nutrients_matrix ~ Coast*Pre.post, data = bl_nutrients_comb, method = "bray")
#                 Df SumOfSqs      R2       F Pr(>F)    
# Coast            2   0.3456 0.07655 16.0757  0.001 ***
# Pre.post         1   0.0686 0.01519  6.3799  0.005 ** 
# Coast:Pre.post   2   0.0375 0.00831  1.7448  0.175    


```

```{r nutrients nmds}
# conduct nmds - this takes a while
set.seed(1032) 
nutrients_ord <- metaMDS(nutrients_matrix, dist	= "bray", k = 2) 
nutrients_ord # stress = 0.04 - going with 2D


# extract species (nutrient) scores
nutrients.species.scores <- as.data.frame(scores(nutrients_ord, "species")) 
nutrients.species.scores$Nutrient <- sub("\\_.*", "", rownames(nutrients.species.scores) ) # extract only the string before the _

# extract the site scores
nutrients.site.scores <- as.data.frame(scores(nutrients_ord, "sites"))  

# add back in metadata
nutrients.site.scores$Unique_ID <- rownames(nutrients.site.scores)
nutrients.site.scores <- merge(meta_df, nutrients.site.scores, by = "Unique_ID")

# calculate centroids
nutrients.cent <- aggregate(cbind(NMDS1, NMDS2) ~ Coast_year, data = nutrients.site.scores, FUN = mean) 
nutrients.cent <- merge(nutrients.cent, meta_df, by = "Coast_year")
```



```{r plot nutrient nmds, fig.height=10, fig.width= 10}
(nutrients_nmds <- 
  ggplot() +
  geom_point(nutrients.site.scores, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast), alpha = 0.4 )+
  geom_text(nutrients.species.scores, mapping = aes(x = NMDS1, y = NMDS2, label = Nutrient)) +
  geom_path(nutrients.cent, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast),
            arrow = arrow(length=unit(0.4,"cm"), ends="last", type = "closed"), size = 1) +
  geom_text(aes(x = -0.5, y = -0.07, label = "Stress = 0.04\nYear - P = 0.001\nCoast - P = 0.001\nYear X Coast - P = 0.001"),
            hjust = 0, size = 5) +
  
  labs(title = "a. Nutrients") +
  theme_bw() + 
  theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) )


```

```{r disturbance nutrients ordination}
# conduct nmds - this takes a while
set.seed(1032)
cc_nutrients_ord <- metaMDS(cc_nutrients_matrix, dist	= "bray", k = 2) 
cc_nutrients_ord # stress = 0.04


# extract species scores
cc_nutrients.species.scores <- as.data.frame(scores(cc_nutrients_ord, "species")) 
cc_nutrients.species.scores$Species <- rownames(cc_nutrients.species.scores) 

# extract the site scores
cc_nutrients.site.scores <- as.data.frame(scores(cc_nutrients_ord, "sites"))  

# add back in metadata
cc_nutrients.site.scores$Unique_ID <- rownames(cc_nutrients.site.scores)
cc_nutrients.site.scores <- merge(meta_df, cc_nutrients.site.scores, by = "Unique_ID")

# add pre-post variable
cc_nutrients.site.scores <- cc_nutrients.site.scores %>%
    mutate(Disturbance = case_when(Year <= 2010 ~ "Pre-disturbance",
                                 Year > 2010 ~ "Post-disturbance"))

# add pre.post_coast variable for calculating centroids/grouping
cc_nutrients.site.scores$Disturbance_coast <- paste0(cc_nutrients.site.scores$Coast, "_", cc_nutrients.site.scores$Disturbance)

# calculate centroids for path
cc_nutrients.cent <- aggregate(cbind(NMDS1, NMDS2) ~ Coast_year, data = cc_nutrients.site.scores, FUN = mean) 
cc_nutrients.cent <- merge(cc_nutrients.cent, meta_df, by = "Coast_year")


## BLEACHING

set.seed(1032) 
# conduct nmds - this takes a while
bl_nutrients_ord <- metaMDS(bl_nutrients_matrix, dist	= "bray", k = 2) 
bl_nutrients_ord # stress = 0.04 

# extract species scores
bl_nutrients.species.scores <- as.data.frame(scores(bl_nutrients_ord, "species")) 
bl_nutrients.species.scores$Species <- rownames(bl_nutrients.species.scores) 

# extract the site scores
bl_nutrients.site.scores <- as.data.frame(scores(bl_nutrients_ord, "sites"))  

# add back in metadata
bl_nutrients.site.scores$Unique_ID <- rownames(bl_nutrients.site.scores)
bl_nutrients.site.scores <- merge(meta_df, bl_nutrients.site.scores, by = "Unique_ID")

# add pre-post variable
bl_nutrients.site.scores <- bl_nutrients.site.scores %>%
    mutate(Disturbance = case_when(Year <= 2019 ~ "Pre-disturbance",
                                 Year > 2019 ~ "Post-disturbance"))

# add pre.post_coast variable for calculating centroids/grouping
bl_nutrients.site.scores$Disturbance_coast <- paste0(bl_nutrients.site.scores$Coast, "_", bl_nutrients.site.scores$Disturbance)

bl_nutrients.cent <- aggregate(cbind(NMDS1, NMDS2) ~ Coast_year, data = bl_nutrients.site.scores, FUN = mean) 
bl_nutrients.cent <- merge(bl_nutrients.cent, meta_df, by = "Coast_year")
```


```{r disturbance nmds plot}

(cc_nutrients_nmds <-
  ggplot() +
  geom_point(data = cc_nutrients.site.scores, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast), alpha = 0.4 )+
  stat_ellipse(data = cc_nutrients.site.scores, 
                 mapping = aes(x = NMDS1, y = NMDS2, group = Disturbance_coast, linetype = Disturbance, color = Coast), type = "t") +
  geom_text_repel(nutrients.species.scores, mapping = aes(x = NMDS1, y = NMDS2, label = Nutrient), max.overlaps = 14) +
  geom_path(cc_nutrients.cent, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast),
            arrow = arrow(length=unit(0.4,"cm"), ends="last", type = "closed"), size = 1) +
  geom_text(aes(x = -0.5, y = -0.07,
                label = "Stress = 0.04\nDisturbance - P = 0.001\nCoast - P = 0.001\nDisturbance X Coast - P = 0.13"),
            hjust = 0, size = 4) +
  labs(title = "b. COTS and Cyclone") +
  scale_linetype_manual(values = c("Pre-disturbance" = "solid", "Post-disturbance" = "dashed")) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) 
    
)



# bleaching
(bl_nutrients_nmds <-
  ggplot() +
  geom_point(data = bl_nutrients.site.scores, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast), alpha = 0.4 )+
  stat_ellipse(data = bl_nutrients.site.scores, 
                 mapping = aes(x = NMDS1, y = NMDS2, group = Disturbance_coast, linetype = Disturbance, color = Coast), type = "t") +
  geom_text_repel(nutrients.species.scores, mapping = aes(x = NMDS1, y = NMDS2, label = Nutrient), max.overlaps = 14) +
  geom_text(aes(x = -0.5, y = -0.07,
            label = "Stress = 0.04\nDisturbance - P = 0.001\nCoast - P = 0.005\nDisturbance X Coast - P = 0.18"),
        hjust = 0, size = 4) +
  geom_path(bl_nutrients.cent, mapping = aes(x = NMDS1, y = NMDS2, colour = Coast),
            arrow = arrow(length=unit(0.4,"cm"), ends="last", type = "closed"), size = 1) +
  labs(title = "c. Bleaching") +
  scale_linetype_manual(values = c("Pre-disturbance" = "solid", "Post-disturbance" = "dashed")) + 
  theme_bw() + 
  theme(plot.title = element_text(size = 22),
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(1.5)), # increase legend text
        legend.title = element_text(size = rel(1.5)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) 
    
)
```

```{r nutrients nmds panel, fig.height=12, fig.width=11}
(nutrients_ord_panel <- 
   ggarrange(nutrients_nmds, ggarrange(cc_nutrients_nmds, bl_nutrients_nmds, ncol = 2, nrow = 1, legend = "none"), ncol = 1, nrow = 2, widths = c(0.6, 0.4), common.legend = T, legend.grob = get_legend(cc_nutrients_nmds), legend = "bottom") )

# ggsave(filename = "output/nutrients_ordination.png", nutrients_ord_panel, height = 12, width = 11)
```

```{r multi panel graph, fig.height=7, fig.width=14}
ggarrange(fish_nmds, nutrients_nmds, nrow = 1, ncol = 2, common.legend = T)

```

